apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: petals-pages
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:admin123@postgres:5432/petals_pages"
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: petals-pages
spec:
  selector:
    app: user-service
  ports:
  - port: 5003
    targetPort: 5003
  type: ClusterIP